# Generated by Django 4.2.7 on 2024-01-15 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 15, 31, 53, 871295), verbose_name='Дата создания'),
        ),
    ]
